database:
  default: mysql
gin:
  domain:  localhost
  port:  8080
cache:
  enable: false
  list: [redis,mongoDB]
mysql:
  user: root
  password: root
  host: localhost
  port: 3306
  name: test
sqlite:
  name: F:/test/test.db

http:
  session_domain: appdomain
  secret: secret
server:
  port: :8080
  appid: appid
  key: secret_key
env:
  mode: debug
auth:
  cas: https://domain


